version: 2
jobs:
  build:
    working_directory: ~/caronaboard
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependencies-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum "elm-package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: build
          command: npm run build
      - save_cache:
          key: dependencies-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum "elm-package.json" }}
          paths:
            - node_modules
            - elm-stuff
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy
            fi
